version: 2.1

orbs:
  sonarqube: escaletech/sonarqube@0.3.0

jobs:
  # Job one with a unique name
  job_1:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"
      - run: echo "Executing step2"
      
  job_2:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML job2!"
      
  job_3:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML job3!"
  
  job_4:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"
      
  job_5:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: echo "Say hello to YAML!"

workflows:
  # Name of workflow
  workflow_1:
    # List of jobs that will runs
    jobs:
      - job_1
      - job_2
      - job_3
      
  workflow_2:
    jobs:
      - job_2
      
  workflow_3:
    jobs:
      - job_3
      
  workflow_4:
    jobs:
      - job_4
      
  workflow_5:
    jobs:
      - job_5

